### ISSUE TITLE
Configs - Update ESLint Configuration

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/PM-Dashboard-v2#154]
I happened to discover a couple nice ESLint configs that I'd like us to add to the package.json. If you happen to come across additional useful ESLint configs, feel free to drop them in a comment reply with a quick explanation of why, and we'll consider adding it too.

Confirmed to add:
```json
"rules": {
      "guard-for-in": "error",
      "prefer-arrow-callback": "error"
    },
```

**Comment by acd124** [comment]
possible rules to look at:

- [ ] [no-unsafe-negation](https://eslint.org/docs/rules/no-unsafe-negation): ["error", { "enforceForOrderingRelations": true }]
- [ ] [no-unsafe-optional-chaining](https://eslint.org/docs/rules/no-unsafe-optional-chaining): ["error", { "disallowArithmeticOperators": true }]
- [ ] [arrow-body-style](https://eslint.org/docs/rules/arrow-body-style): ["error", "as-needed"]
- [ ] [block-scoped-var](https://eslint.org/docs/rules/block-scoped-var)
- [ ] [eqeqeq](https://eslint.org/docs/rules/eqeqeq)
- [ ] [max-depth](https://eslint.org/docs/rules/max-depth)
- [ ] [max-nested-callbacks](https://eslint.org/docs/rules/max-nested-callbacks)
- [ ] [no-else-return](https://eslint.org/docs/rules/no-else-return)
- [ ] [no-lonely-if](https://eslint.org/docs/rules/no-lonely-if)
- [ ] [no-throw-literal](https://eslint.org/docs/rules/no-throw-literal)
- [ ] [prefer-promise-reject-errors](https://eslint.org/docs/rules/prefer-promise-reject-errors)
- [ ] [no-unneeded-ternary](https://eslint.org/docs/rules/no-unneeded-ternary)
- [ ] [no-var](https://eslint.org/docs/rules/no-var)
- [ ] [object-shorthand](https://eslint.org/docs/rules/object-shorthand)
- [ ] [operator-assignment](https://eslint.org/docs/rules/operator-assignment)
- [ ] [prefer-const](https://eslint.org/docs/rules/prefer-const)
- [ ] [prefer-destructuring](https://eslint.org/docs/rules/prefer-destructuring)
- [ ] [prefer-exponentiation-operator](https://eslint.org/docs/rules/prefer-exponentiation-operator)
- [ ] [prefer-object-spread](https://eslint.org/docs/rules/prefer-object-spread)
- [ ] [prefer-rest-params](https://eslint.org/docs/rules/prefer-rest-params)
- [ ] [prefer-spread](https://eslint.org/docs/rules/prefer-spread)
- [ ] [prefer-template](https://eslint.org/docs/rules/prefer-template) debatable since sometimes not as pretty
- [ ] [spaced-comment](https://eslint.org/docs/rules/spaced-comment)
- [ ] [yoda](https://eslint.org/docs/rules/yoda)

Formatted as a task list to allow easy display of which to use and which to not use

**Comment by jamescd18** [comment]
Arrow-body-style: always? Not sure about this one. I feel like part of the whole point of arrow functions is to allow much simpler one-liner functions.

**Comment by acd124** [comment]
> **arrow-body-style:** always? Not sure about this one. I feel like part of the whole point of arrow functions is to allow much simpler one-liner functions.
> 
Default is as-needed, which would remove brackets where possible, while leaving more complicated/multi-line arrow functions alone
> **max-depth:** what were you planning to set this at?
> 
Probably something reasonable like 3-4, not sure (default is 4)
> **max-nested-callbacks:** what were you planning to set this at?
> 
Probably something like, like maybe 2-3 (default is 10) trying to reduce callback hell
> **operator-assignment:** always or never?
> 
Always, to use shorthand more often, but it will not suggest the shorthand when it is logically different. This might be left out if different shorthand operators aren't desired to be used, however I think for the most part more complicated operators would not be used in places where this rule would apply
