### ISSUE TITLE
General - Test `database-setup` Branch

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/PM-Dashboard-v2#383]
## Background:
The `database-setup` branch was created in order to implement the messy and sweeping changes it took to properly configure and set up the back-end to query data from the database.

## Description:
Prior to merging the `database-setup` branch into `main`, we need to be confident that the application, as run from the `database-setup` branch, works properly in its entirety. Run the application locally and thoroughly run various manual tests of your choosing. Document the manual tests you performed in a bullet list in a comment reply on this ticket. Be sure to specify any odd behaviors or broken features you encounter to review with the team.

**Comment by acd124** [comment]
Viewing specific Change Requests usually does not work, often erroring with `cannot read property map of undefined` from `src/components/change-requests/change-request-details/change-request-details/change-request-details.tsx:46`. This is likely because of some missing implementation for specific change request types. The only change request that looks to work has crId 5.

**Comment by RChandler234** [comment]
Here are the notes I had after testing the ‘database-setup’ branch; I didn’t find any problems that I felt immediately needed to be addressed, mostly just weird formatting things, let me know if there’s anything else I should test/ if I should address any of the minor issues I mentioned:

-Loading into home page as admin works fine
-All the links on project details link to rick astely (assuming that’s a good thing)
-Not sure what the active button with little arrows next to it is for, just moves the text slightly (same with the rest of the little arrow things)
this thing:
<img width="14" alt="button" src="https://user-images.githubusercontent.com/29521172/147511901-1ed6786c-f5df-4171-a42c-97fbee11ef0e.png">
-Trying to open the change request link in a project doesn’t work if I try to open it in a new tab, but otherwise it works fine (same for work package links)
-Workpackage info dropdown within project pages works well
-Workpackage links work
-reloading the page always makes you sign back in as admin
-The implemented changes tab currently just has the placeholder (“list of changes”) might be nice to see what the format for this would actually look like

-All the projects and subsequent links work in the projects tab,I went through testing that each link within each project worked as expected, checked generally to make sure the content looked correct, and trying some weird things like opening in a new tab, etc.




-Weird format inconsistencies in some change requests: (seems to specifically be in the “new function” type)
Most Change Requests:

<img width="908" alt="normal" src="https://user-images.githubusercontent.com/29521172/147511753-300abb21-d2dd-431b-bcf6-c9035b678bd8.png">

“New Function” change request :
<img width="897" alt="new function" src="https://user-images.githubusercontent.com/29521172/147511818-7e0f81bf-887f-4393-906e-e4d6d5ae1018.png">


-Not sure if the new change request page works because I just get a submitted message when I submit the page, but I’ve messed around with all the textboxes/dropdowns/buttons and they seem to work fine. 
-My only note would be that I’m not sure if the start date button works because it still looks like this even after selecting a date:
<img width="189" alt="startdate" src="https://user-images.githubusercontent.com/29521172/147511860-b3d4d24e-5595-48ae-918c-bf8ee7771a56.png">

-The settings dropdown successfully takes you to the "settings" page
-the logout dropdown doesn't currently do anything

-tried testing using different users and got all the same results (assuming all the permissions are the same for now)
-only note for users is that there are two sets of admin, leadership and user options in the dropdown, and only one option for guest:
<img width="319" alt="users" src="https://user-images.githubusercontent.com/29521172/147512171-67500e48-dd33-4749-a49c-e90a425b01bb.png">

**Comment by jamescd18** [comment]
Thank you so much!! Let me see if I can cover everything:
- we should create an improvement ticket to remove the duplicate user roles in the development login bypass bit 
- we should create a bug ticket to note the little up down arrow thing showing up. You'll need to make sure to be specific about OS and browser and stuff of where you see it. Creating a ticket will ensure we note it down, allow others to chime in and specify they experience it too, allow us to acknowledge it, and enable us to investigate it at a later point in time cuz it's a low-priority bug that isn't impacting usage or functionality from what I can see. Put in the ticket that I suspect it is part of a larger scroll bar thingy that may or may not be avoided by adjusting our CSS. 
- Rick astley links are perfect as expected
- we should create an improvement ticket for deep linking. Basically we need to capture the visited url before forcing the redirect to login, and then push the user back to the visited url after login. I'm aware it is an issue, just couldn't get it to work when I built the login. 
- re-login on reload is as expected. Hopefully later one day we can get the login authentication security features to work better, but for now they just force more frequent logins. 
- submit change request page not working is as-expected
- We should create an improvement ticket for the formatting inconsistencies
- I think you need to click the logout button twice for it to work.  Probably should submit a bug ticket if the button doesn't work or takes two clicks. 
-

**Comment by jamescd18** [comment]
After the testing was completed I moved forward with working on resolving merge conflicts from the 150+ commits of drift from main. Ended up discovering relatively unsolvable issues with #309 having been merged into main and not tested properly with prisma to discover that things were missed and that prisma might not properly support it as an implicit many-to-many relationship. Ended up undoing and going back to single optional project lead and also creating #409 to handle a 2nd try better approach to achieving the same results for end users.
