### ISSUE TITLE
General - Test `main` branch

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/PM-Dashboard-v2#384]
## Background:
The `database-setup` branch was created in order to implement the messy and sweeping changes it took to properly configure and set up the back-end to query data from the database.

## Description:
After completing #383 and merging the `database-setup` branch into `main`, we need to be confident that the application, as run from the `main` branch, works properly in its entirety. Run the application locally and thoroughly run various manual tests of your choosing. Ensure you also run any manual tests performed and documented in #383. Document the manual tests you performed in a bullet list in a comment reply on this ticket. Be sure to specify any odd behaviors or broken features you encounter to review with the team.

**Comment by jpwaves** [comment]
**Tests I did on `main`:**
- Same tests conducted in #383
- Checked if data from Postgres db matched what was displayed on the page for projects, work packages, and change requests
- Messed with filters and sorters on the project and change request tables
I couldn't think of anything else to test after these tests, so if there is something I missed testing I can go do that.

**Observations from testing:**
- **General**
  - Trying to open any link to a new tab opens the dashboard to the login page. This includes links to change requests, projects, work packages, etc.
  - The logout button still doesn't work. I tried spam clicking the button as suggested in #383 but it still didn't work.
  - There are still duplicate roles on the login page
    - Screenshot: ![dup-login-roles](https://user-images.githubusercontent.com/48561685/148854841-977e0e7d-73c9-400a-90cc-b81c996a3993.png)
  - Settings page only shows the username; I think this is expected.
  - All quick links on the home page work
  - All navigation buttons link to the correct pages
  - Profile drop-down in top-right corner works.
  - Loading the projects and change requests table resets any filters/sorting on the table that was there previously, if any.
    - SIDE NOTE: It was a bit of a pain resetting the projects table filter by going through each filter and setting it to the default. It'd be nice if there was a "Clear Filters" button or something of the like to do this automatically without having to do it manually or reload the page.
  - The project and change request tables have weird positioning when the viewport is shrunk; I was doing some of the tests on split screen and discovered this. For the projects table, the table is weirdly positioned in relation to the filters. For the change requests table, the label for the last column is slightly overflowing.
    - Screenshots:
![weird-project-formatting](https://user-images.githubusercontent.com/48561685/148876497-c64e1f2f-73ad-4bc3-b82e-a4790921dad9.png)
![cr-table-weird-formatting](https://user-images.githubusercontent.com/48561685/148876506-235fc284-25c8-46ef-8d46-c9c17983db04.png)

- **Project**
  - Projects with WBS 1.25.0 and 1.23.0 both have a duration of 0 weeks, but 1.25.0 is marked as "Complete" whereas 1.23.0 is marked as "Inactive". Not sure if this is intended or not.
  - The "Deliverables" section in work packages displays the incorrect data (displays the "Extended Activities" data instead). Other than this, all the project and work package data appear to accurately reflect what is in the database.
    -  Screenshots: 
![wp-1-incorrect-deliverables](https://user-images.githubusercontent.com/48561685/148856532-ab534b32-66e6-4484-8473-fbf2b51c370e.png)
![wp-2-incorrect-deliverables](https://user-images.githubusercontent.com/48561685/148856556-45d71957-e94b-46b6-bb07-5265c714c594.png)
![wp-3-incorrect-deliverables](https://user-images.githubusercontent.com/48561685/148856604-16f0933b-dd3f-4b55-aab1-03c039560a18.png)
  - There are instances where the link to change requests from the projects or work package pages cause the change request page to load scrolled down already. This occurs when you go to a specific change request, go back to the previous page, and then go back to that same change request again.
    - Screenshot (for what the weird scrolled down behavior shows on load):
![onload-cr-page-from-cr2-link](https://user-images.githubusercontent.com/48561685/148876128-f95c68c5-eb23-4e07-9295-a969656e3603.png)
  - The "Expected Progress" and "Timeline Status" fields in the project details are currently blank for all projects. Not sure if this is expected or not.
  - I can't open rows of the projects table to a new tab when I right click. Not sure if this is expected or not
    - Screenshot:
![projects-table-no-opentonewtab](https://user-images.githubusercontent.com/48561685/148878238-1d9ab1c9-ec89-4196-bbfa-9fb0b04395ff.png)

- **Change**
  - Change requests that are indicated as "Accepted" still have the accept/deny buttons on their details page. This could likely be resolved by conditionally displaying those buttons, which should be a quick and easy fix I think. One example is change request 1 which is indicated as implemented and shouldn't need to be accepted or denied at that point.
    - Screenshot:
![cr-1-accepted-but-has-accept-btn](https://user-images.githubusercontent.com/48561685/148876728-30b3c2c6-e6e4-4fbc-9bd2-e5d1b38487a9.png)
  - The "Implemented Changes" section on the change request details page is still "list of changes"
  - Within the database, some records in the `Change_Request` table have a blank value or `f` as their value for the `accepted` column. Both of those values for that column result in the change request being displayed as "Open" on the dashboard. I'm not sure if this is intentional or an error in data input.
  - Review notes for change requests are not displayed on the detail page.
  - There is some weird formatting with the "Impact" section within the "Standard Change Request Details" section where the indention/alignment doesn't match with the "Why" section above it. This occurs when the viewport is horizontally shrunk.
    - Screenshot: 
![standard-cr-details-weird-format-split-screen](https://user-images.githubusercontent.com/48561685/148877204-19a961fb-5edf-4761-8871-c446cbdb31a7.png)
  - Stage Gate Change Request 5 states that its value for "Confirm WP Completed" is "NO" but the database indicates that the confirm completed is true. All other data for the other change requests are accurate though.
    - Screenshots:
![stagegate-cr-5-confirm-inconsistent](https://user-images.githubusercontent.com/48561685/148877341-5b71746f-122c-4816-990d-6928090f1a9a.png)
![stagegate-cr-5-db-data](https://user-images.githubusercontent.com/48561685/148877353-2b322f86-bda2-4f3b-8fd0-972ab8a0fbaf.png)
  -  Submitting a new change request still doesn't work.
  - The new change request form doesn't seem to have any validation. I can also submit the form without filling out anything and leaving everything either blank or their default value; not sure if this is desired or not.
    - Screenshot: 
![new-cr-no-validation-1](https://user-images.githubusercontent.com/48561685/148877563-5087e91d-2532-4b46-8f38-18965fe1d1c9.png)
![new-cr-no-validation-2](https://user-images.githubusercontent.com/48561685/148877569-30c1be73-4257-45ae-a700-9722c21de257.png)
  - The new change request form also seems to be missing inputs for describing "Estimation Error", "School Work", "Manufacturing Issues", and "Rules Compliance" for the "Why" section of a change request.
    - Screenshot:  
![new-cr-why-section](https://user-images.githubusercontent.com/48561685/148877763-d85dff2f-93c4-4ec2-b872-df321e3e67aa.png)
  - The "Start Date" input on the new change request form still doesn't work. It does clear the existing date that was manually entered when a date is chosen from the calendar popup though.
  - I'm not really sure what the "Who is Required for Design Review?" section is for since I couldn't figure out what the input for that would correspond to on the details page. I also don't remember seeing any column in any of the tables of the database that seemed likely for the input of that form to be added to.
  - The "Type" input has "Initiation" as an option; not sure if this is supposed to be "Activation" instead of "Initiation".
    - Screenshot:
![new-cr-initiation-type](https://user-images.githubusercontent.com/48561685/148877945-d41825ec-59d1-403a-89ea-894f9edcd0bd.png)
  - When sorting by the "Reviewed" or "Implemented" columns in the change request table, it sorts rows with blank/missing dates above rows with dates. Not sure if this is desired behavior.
  - Within the database, some change requests have the type `ISSUE`. I'm assuming that this type engulfs both a "Design Issue" change request and a "New Function" change request, but I'm not completely sure. 
 
I'll add to this if I think of anything else I should test for the `main` branch. Also, if you need me to add any screenshots for any of these bullets, I can go get those.

**Comment by jamescd18** [comment]
Before this can be closed, we need to go through all of Justin's really thorough notes and register / create any issues that aren't already created.

**Comment by jpwaves** [comment]
Summary of `main` testing notes:
- logout broken
- duplicate roles on login
- add clear filter btn
- improve responsive layout for project and change request tables and filters
- projects with duration of 0 wks are sometimes marked "Complete" or "Inactive"
- deliverables has incorrect data 
- bug with loading cr details (loads page already scrolled after revisiting the cr details page)
- conditionally show accept/deny btns 
- implement "Implemented Changes" section
- cr's marked as open if their `accepted` value is `f` or blank
- review notes not displayed on cr details page
- improve responsive layout formatting on cr details page for standard cr details section
- confirm wp completed is "NO" for stage gate cr but is true in db
- submitting new cr is broken
- no validation on new change request form
- new change request form missing inputs for different categories of "why" section
- start date input on new change request form is broken
- "who is required for design review?" section has no clear reference in db tables, may not be necessary in the form
- type input has "initiation" instead of "activation"
- cr db type ISSUE corresponds to both a "Design issue" and "New Function", don't understand why ISSUE engulfs both

**Comment by kevinyu328** [comment]
Everything has been addressed with new tickets.
