### ISSUE TITLE
Research - Testing with Jest

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/PM-Dashboard-v2#7]
Research the Jest testing package to understand how testing could work, and such like that.

**Comment by jamescd18** [comment]
This is great to hear! What sorta stuff will we need to do to set up Jest in the current repo?

**Comment by eshwaribhide** [comment]
> This is great to hear! What sorta stuff will we need to do to set up Jest in the current repo?

I believe this was described in the comments above. But there are two ways to configure jest, either through `package.json` or through a `jest.config.js` or `jest.config.ts` file. I believe I linked this [article](https://jestjs.io/docs/en/configuration) which showed how to do it through `jest.config.js` and also on Jest's website [they describe how to do it](https://jestjs.io/docs/en/configuration).

**Comment by jamescd18** [comment]
I was playing with it yesterday and it seems like Jest is included with react-scripts. Are there any configurations we actually would want to adjust?

**Comment by eshwaribhide** [comment]
I kept on editing this comment again and again because I remember you saying, and also from looking it up, that create-react-app basically gives you Jest, and had added a thing at the bottom saying that and that I didn't necessarily think we needed to do anything extra. and then for some reason second-guessed it and took it out, which was dumb and idk why. So, I don't actually think we need to adjust any configurations.

I think though that maybe one thing to do is add `react-test-renderer` for adding snapshots, just install with npm.
